# Water Softener Monitor - ATOM S3 Web Installer Config
# For M5Stack ATOM S3 Lite hardware
# Includes web server (ESP-IDF framework)

substitutions:
  name: "water-softener-monitor"
  version: "1.9.2-s3"

esphome:
  name: "${name}"
  friendly_name: Water Softener Monitor
  comment: Water Softener Monitor (ATOM S3)
  name_add_mac_suffix: true
  project:
    name: "rmaher001.water-softener-monitor"
    version: "${version}"

# Dashboard import for ESPHome Dashboard integration and updates
dashboard_import:
  package_import_url: github://rmaher001/water-softener-monitor/src/water-softener-s3-webinstall.yaml@1.9.2
  import_full_config: false

# Include the S3 core package for all sensor/config logic
packages:
  water_softener: !include water-softener-s3-core.yaml

# API for Home Assistant integration
api:

# OTA updates - no password for easy management
ota:
  - platform: esphome

wifi:
  power_save_mode: none
  ap:
    ssid: "Water Softener Hotspot"
    password: "configme123"
    ap_timeout: 0s
