# Water Softener Monitor - Development Config
# This config is used for testing changes before merging to master

substitutions:
  device_name: "water-softener-dev"
  friendly_name: "Water Softener Dev"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

# For local development: Include package directly
packages:
  water_softener: !include water-softener-package.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

# WiFi configuration for development
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Fallback hotspot if WiFi fails
  ap:
    ssid: "${device_name}-Fallback"
    password: "configme123"

# For testing branches: Switch to this format
# packages:
#   water_softener: github://rmaher001/water-softener-monitor/src/water-softener-package.yaml@feature/branch-name
