# Water Softener Monitor - Production Config
# This is the production configuration that uses the package from GitHub

substitutions:
  device_name: "water-softener"
  friendly_name: "Water Softener Monitor"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  water_softener: github://rmaher001/water-softener-monitor/src/water-softener-package.yaml@master
