# Water Softener Monitor - Web Installer Config
# This config is used to build firmware for the web installer
# Uses generic name with MAC suffix for unique device names

substitutions:
  device_name: "water-softener"
  friendly_name: "Water Softener"

# Override esphome section to add MAC suffix before package
esphome:
  name: ${device_name}
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "water-softener.monitor"
    version: "2.0.0"

# Enable ESPHome Dashboard adoption for clean entity IDs
dashboard_import:
  package_import_url: github://rmaher001/water-softener-monitor/src/water-softener-package.yaml@master
  import_full_config: false

# Include the main package for all sensor/config logic
packages:
  water_softener: !include water-softener-package.yaml

# WiFi configured via Improv Serial - no hard-coded credentials
wifi:
  ap:
    ssid: "Water Softener"
