# Water Softener Monitor - Web Installer Config
# This config is used to build firmware for the web installer
# Uses generic name with MAC suffix for unique device names

substitutions:
  device_name: "water-softener"
  friendly_name: "Water Softener"

# Override esphome section with MAC suffix for unique device names
esphome:
  name: ${device_name}
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "rmaher001.water-softener-monitor"
    version: "4.0.0"

# Dashboard import for ESPHome Dashboard integration and updates
dashboard_import:
  package_import_url: github://rmaher001/water-softener-monitor/src/water-softener-webinstall.yaml@master
  import_full_config: false

# Include the main package for all sensor/config logic
packages:
  water_softener: !include water-softener-package.yaml

# WiFi configured via Improv Serial - no hard-coded credentials
wifi:
  ap:
    ssid: "Water Softener"
    password: "12345678"
    ap_timeout: 0s  # Never timeout AP mode
