# Minimal test config - matches Bluetooth Proxy structure
esphome:
  name: water-softener
  friendly_name: Water Softener
  name_add_mac_suffix: true

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: esp-idf

wifi:
  ap:

api:

logger:
  deassert_rts_dtr: true

ota:
  - platform: esphome
