# Water Softener Monitor - Production Config
# Used for the production unit - gets updates from GitHub master branch like all users

substitutions:
  device_name: "water-softener-prod"
  friendly_name: "Water Softener Prod"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  water_softener: github://rmaher001/water-softener-monitor/src/water-softener-package.yaml@master
