# Water Softener Monitor - ATOM S3 Dev Config
# For testing/development with M5Stack ATOM S3
# Uses local includes for fast iteration

substitutions:
  name: "water-softener-monitor-s3-dev"
  version: "1.9.3-dev"

esphome:
  name: "${name}"
  friendly_name: Water Softener Monitor (S3 Dev)
  comment: Water Softener Monitor (ATOM S3 Dev)
  name_add_mac_suffix: false
  project:
    name: "rmaher001.water-softener-monitor"
    version: "${version}"

# Dashboard import for ESPHome Dashboard testing
dashboard_import:
  package_import_url: github://rmaher001/water-softener-monitor/src/water-softener-s3-webinstall.yaml@master
  import_full_config: false

# Include the S3 core package locally for fast development
packages:
  water_softener: !include water-softener-s3-core.yaml

# API for Home Assistant integration
api:

# OTA updates
ota:
  - platform: esphome

# WiFi configuration from secrets
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  ap:
    ssid: "Water Softener Hotspot"
    password: "configme123"
    ap_timeout: 0s
